# Generated by Django 4.2.5 on 2023-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='name')),
                ('storyline', models.TextField(verbose_name='description')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('about', models.CharField(max_length=30, verbose_name='about')),
                ('url', models.URLField(max_length=30, verbose_name='url')),
            ],
            options={
                'verbose_name': 'stream',
                'verbose_name_plural': 'Streams',
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
