# Generated by Django 4.2.5 on 2023-10-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movielist_cast_movielist_director_movielist_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('history', 'History')], max_length=20, null=True, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
