# Generated by Django 4.2.5 on 2023-10-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movielist_genre_alter_movielist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='url',
            field=models.URLField(max_length=100, verbose_name='url'),
        ),
    ]
