# Generated by Django 4.2.5 on 2023-10-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_streamplatform_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='movies.streamplatform', verbose_name='platform'),
        ),
    ]
