# Generated by Django 4.2.5 on 2023-10-20 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0006_movielist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='cast',
            field=models.ManyToManyField(related_name='acted_in_movies', to=settings.AUTH_USER_MODEL, verbose_name='cast'),
        ),
    ]
