# Generated by Django 4.2.5 on 2023-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='average rating'),
        ),
    ]
