# Generated by Django 4.2.5 on 2023-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movielist_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='number_rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='number of rating'),
        ),
    ]
